server:
  port: 8081

spring:
  application:
    name: app-admin-api
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: verySecretKeyThatShouldBeAtLeast32BytesLongForHS256Algorithm
  expiration: 86400000 # 24시간
